export const REQUEST_BANNER = 'REQUEST_BANNER';
export const RECEIVE_BANNER = 'RECEIVE_BANNER';
export const REQUEST_PRO_LIST = 'REQUEST_PRO_LIST';
export const RECEIVE_PRO_LIST = 'RECEIVE_PRO_LIST';
export const RECEIVE_PRO_LIST_FOR_REFRESH = 'RECEIVE_PRO_LIST_FOR_REFRESH';
export const REQUEST_ALL_SHARE_ORDER = 'REQUEST_ALL_SHARE_ORDER';
export const RECEIVE_ALL_SHARE_ORDER = 'RECEIVE_ALL_SHARE_ORDER';
export const RECEIVE_ALL_SHARE_ORDER_FOR_REFRESH = 'RECEIVE_ALL_SHARE_ORDER_FOR_REFRESH';
