export const REQUEST_BANNER = 'REQUEST_BANNER';
export const RECEIVE_BANNER = 'RECEIVE_BANNER';
export const REQUEST_PRO_LIST = 'REQUEST_PRO_LIST';
export const RECEIVE_PRO_LIST = 'RECEIVE_PRO_LIST';
